### ISSUE TITLE
No functions appear in `M-x`. How to use that?

### ISSUE THREAD

**Issue by quarkquartet** [emacs-grammarly/grammarly#6]
I installed this with Melpa. If I write the example code to check "Hello world" in `.el` file and manually execute them by `C-x C-e`, it works well. However, if I write `(require 'grammarly)` or `(use-package grammarly :config (setq username....)` I get nothing. I want to use it in my org-mode, markdown, latex... etc. I try to use `M-x` to find the functions defined by grammarly.el, but I found nothing.

How to use this nice package?

**Comment by jcs090218** [comment]
Hi, this package is a library and not for user level hence no `M-x`, etc. See https://github.com/emacs-grammarly/grammarly#examples.
