### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by randy-shi** [emacs-grammarly/grammarly#9]

**Comment by jcs090218** [comment]
The README section say it all, https://github.com/emacs-grammarly/grammarly#-examples.

If you are looking for the complete client, you should checkout

- https://github.com/emacs-grammarly/flycheck-grammarly
- https://github.com/emacs-grammarly/flymake-grammarly

Or LSP based solutions

- https://github.com/emacs-grammarly/lsp-grammarly
- https://github.com/emacs-grammarly/eglot-grammarly
